name: 'David & Carly'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7007651599124074
title: 'David & Carly Get Married'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8248303113505244
  lightness: 0.8614848298020661
  saturation: 0.7241744895000011
  rhythmicContrast: 0.9656737640034407
purpose: []
