name: 'David & Carly'
favicon: null
layout_spectrum: 0.97202
typography_spectrum: 0.94951
title: 'David & Carly'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6aa0e8'
    - '#a5cbfc'
    - '#baa882'
    - '#050925'
    - '#7c6a48'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
