name: 'David & Carly'
favicon: null
layout_spectrum: 0.97202
typography_spectrum: 0.94951
title: 'David & Carly'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedede'
    - '#b3b1b2'
    - '#b39595'
    - '#d0d0d0'
    - '#c4c4c4'
  brandStrength: 0.8248303113505244
  lightness: 0.8614848298020661
  saturation: 0.7241744895000011
  rhythmicContrast: 0.9656737640034407
purpose: []
